Repository aaronstz/be_java_hisp_w31_g06, pull requests merged in 2025-04, with the labels that each got.

#1 [SCRUM-6] FEAT: Get All Products in DB
  src/main/java/com/mercadolibre/socialmeli/VERSION
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/repository/IProductRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/ProductRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/IProductService.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
  src/main/resources/products.json
Labels: Juani approves

#2 Cargar usuarios desde Json
  src/main/java/com/mercadolibre/socialmeli/repository/UserRepositoryImpl.java
Labels: Juani approves

#3 [SCRUM-6] FEAT: Create posts, fixed price attribute for Product entity
  src/main/java/com/mercadolibre/socialmeli/VERSION
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/dto/PostDto.java
  src/main/java/com/mercadolibre/socialmeli/entity/Post.java
  src/main/java/com/mercadolibre/socialmeli/exception/AlreadyExistsException.java
  src/main/java/com/mercadolibre/socialmeli/exception/ExceptionController.java
  src/main/java/com/mercadolibre/socialmeli/repository/IProductRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/ProductRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/IProductService.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
  src/main/resources/posts.json
  src/main/resources/user.json
Labels: Juani approves

#4 Us 0006
  src/main/java/com/mercadolibre/socialmeli/controller/MeliSocialController.java
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/controller/UserController.java
  src/main/java/com/mercadolibre/socialmeli/dto/ExceptionDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/FollowerCountDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/FollowingPostDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/PostDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/ProductDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/UserDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/UserListDto.java
  src/main/java/com/mercadolibre/socialmeli/entity/User.java
  src/main/java/com/mercadolibre/socialmeli/repository/IProductRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/IUserRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/ProductRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/repository/UserRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/IProductService.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/UserServiceImpl.java
  src/main/resources/user.json
Labels: Juani approves, Aaron approves

#6 Scrum 10 us 0009 bercellini erika
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/exception/ExceptionController.java
  src/main/java/com/mercadolibre/socialmeli/repository/IProductRepository.java
  src/main/java/com/mercadolibre/socialmeli/service/IProductService.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
  src/main/resources/user.json
Labels: Juani approves

#8 Scrum 5 us 0004 gerez aaron
  src/main/java/com/mercadolibre/socialmeli/VERSION
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/controller/UserController.java
  src/main/java/com/mercadolibre/socialmeli/dto/FollowingListDto.java
  src/main/java/com/mercadolibre/socialmeli/entity/Following.java
  src/main/java/com/mercadolibre/socialmeli/repository/IUserRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/UserRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/IUserService.java
  src/main/java/com/mercadolibre/socialmeli/service/UserServiceImpl.java
Labels: Juani approves

#10 Implemento us 0011
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/dto/PostDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/PromoPostCountDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/UserDto.java
  src/main/java/com/mercadolibre/socialmeli/entity/Post.java
  src/main/java/com/mercadolibre/socialmeli/repository/IUserRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/ProductRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/repository/UserRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/IProductService.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/UserServiceImpl.java
  src/main/resources/posts.json
  src/main/resources/user.json
Labels: Aaron approves, Tamara approves

#11 US 0010: Llevar a cabo la publicación de un nuevo producto en promoción
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/dto/PostDto.java
  src/main/java/com/mercadolibre/socialmeli/entity/Post.java
  src/main/java/com/mercadolibre/socialmeli/service/IProductService.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
  src/main/resources/posts.json
  src/main/resources/user.json
Labels: Aaron approves, Tamara approves, Erika approves

#12 Scrum 9 us 0008 mecozzi tamara
  src/main/java/com/mercadolibre/socialmeli/controller/UserController.java
  src/main/java/com/mercadolibre/socialmeli/service/IUserService.java
  src/main/java/com/mercadolibre/socialmeli/service/UserServiceImpl.java
Labels: Aaron approves, Erika approves

#14 [SCRUM-13] FEAT: implement get promos by seller
  src/main/java/com/mercadolibre/socialmeli/VERSION
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/repository/IProductRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/ProductRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/IProductService.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
  src/main/resources/posts.json
  src/main/resources/user.json
Labels: Tamara approves, Erika approves, Fer approves

#18 (bonus) us 0014
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/repository/IUserRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/UserRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/IProductService.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/UserServiceImpl.java
Labels: Juani approves, Aaron approves, Erika approves

#19 Crear DTO Message
  src/main/java/com/mercadolibre/socialmeli/controller/UserController.java
  src/main/java/com/mercadolibre/socialmeli/dto/MensajeDto.java
  src/main/java/com/mercadolibre/socialmeli/service/IUserService.java
  src/main/java/com/mercadolibre/socialmeli/service/UserServiceImpl.java
Labels: Aaron approves, Tamara approves, Erika approves, Fer approves

#20 Scrum 13 us 0012 gerez aaron
  src/main/java/com/mercadolibre/socialmeli/VERSION
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/dto/PromoPostDto.java
  src/main/java/com/mercadolibre/socialmeli/service/IProductService.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
Labels: Juani approves, Tamara approves, Erika approves, Fer approves

#21 MERGE V0.1.7
  .DS_Store
  README.md
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/mercadolibre/socialmeli/VERSION
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/controller/UserController.java
  src/main/java/com/mercadolibre/socialmeli/dto/ExceptionDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/FollowDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/FollowerCountDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/FollowingListDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/FollowingPostDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/MensajeDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/PostDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/ProductDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/PromoPostCountDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/PromoPostDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/UserDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/UserListDto.java
  src/main/java/com/mercadolibre/socialmeli/entity/Follow.java
  src/main/java/com/mercadolibre/socialmeli/entity/Post.java
  src/main/java/com/mercadolibre/socialmeli/entity/Product.java
  src/main/java/com/mercadolibre/socialmeli/entity/User.java
  src/main/java/com/mercadolibre/socialmeli/exception/BadRequestException.java
  src/main/java/com/mercadolibre/socialmeli/exception/ConflictException.java
  src/main/java/com/mercadolibre/socialmeli/exception/ExceptionController.java
  src/main/java/com/mercadolibre/socialmeli/exception/NotFoundException.java
  src/main/java/com/mercadolibre/socialmeli/repository/IProductRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/IUserRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/ProductRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/repository/UserRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/IProductService.java
  src/main/java/com/mercadolibre/socialmeli/service/IUserService.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/UserServiceImpl.java
  src/main/resources/diagramas.drawio.png
  src/main/resources/posts.json
  src/main/resources/products.json
  src/main/resources/user.json
Labels: Tamara approves, Erika approves

#25 Handler validation errors
  pom.xml
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/controller/UserController.java
  src/main/java/com/mercadolibre/socialmeli/dto/PostDto.java
  src/main/java/com/mercadolibre/socialmeli/exception/ConflictException.java
  src/main/java/com/mercadolibre/socialmeli/exception/ExceptionController.java
Labels: Tamara approves, Erika approves
