Repository aaronstz/be_java_hisp_w31_g06, pull requests merged in 2025-05, with the labels that each got.

#27 se agrega base de factory para testing
  .DS_Store
  src/.DS_Store
  src/test/java/com/mercadolibre/socialmeli/util/TestDataFactory.java
  src/test/resources/application.properties
Labels: Juani approves, Fer approves

#28 Scrum 43 t 0010 mecozzi tamara
  src/main/java/com/mercadolibre/socialmeli/repository/IUserRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/ProductRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/repository/UserRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
  src/test/java/com/mercadolibre/socialmeli/BeJavaHispW31G06ApplicationTests.java
  src/test/java/com/mercadolibre/socialmeli/controller/ProductsControllerTests.java
  src/test/java/com/mercadolibre/socialmeli/repository/ProductRepositoryTests.java
  src/test/java/com/mercadolibre/socialmeli/service/ProductServiceTest.java
  src/test/java/com/mercadolibre/socialmeli/util/TestDataFactory.java
Labels: Juani approves, Fer approves

#30 Scrum 41 us T0006 torres fernando
  src/test/java/com/mercadolibre/socialmeli/BeJavaHispW31G06ApplicationTests.java
  src/test/java/com/mercadolibre/socialmeli/controller/ProductsControllerTests.java
  src/test/java/com/mercadolibre/socialmeli/repository/UserRepositoryTests.java
  src/test/java/com/mercadolibre/socialmeli/service/ProductServiceTest.java
  src/test/java/com/mercadolibre/socialmeli/service/UserServiceTests.java
  src/test/java/com/mercadolibre/socialmeli/util/TestDataFactory.java
Labels: Tamara approves

#31 T0007 test unitarios y de integracion
  src/test/java/com/mercadolibre/socialmeli/BeJavaHispW31G06ApplicationTests.java
  src/test/java/com/mercadolibre/socialmeli/controller/UsersControllerTests.java
  src/test/java/com/mercadolibre/socialmeli/service/UserServiceTests.java
Labels: Tamara approves

#32 T-0001 Follow method unit and integration tests
  src/test/java/com/mercadolibre/socialmeli/BeJavaHispW31G06ApplicationTests.java
  src/test/java/com/mercadolibre/socialmeli/controller/UsersControllerTests.java
  src/test/java/com/mercadolibre/socialmeli/service/UserServiceTests.java
  src/test/java/com/mercadolibre/socialmeli/util/TestDataFactory.java
Labels: Tamara approves

#34 T-0003 Verificar que el tipo de ordenamiento alfabético exista
  src/main/java/com/mercadolibre/socialmeli/dto/FollowingListDto.java
  src/test/java/com/mercadolibre/socialmeli/BeJavaHispW31G06ApplicationTests.java
  src/test/java/com/mercadolibre/socialmeli/controller/UsersControllerTests.java
  src/test/java/com/mercadolibre/socialmeli/service/UserServiceTests.java
  src/test/java/com/mercadolibre/socialmeli/util/TestDataFactory.java
Labels: Tamara approves, Fer approves

#33 T-0002 Verificar que el usuario a dejar de seguir exista
  src/main/java/com/mercadolibre/socialmeli/controller/UserController.java
  src/test/java/com/mercadolibre/socialmeli/BeJavaHispW31G06ApplicationTests.java
  src/test/java/com/mercadolibre/socialmeli/controller/UsersControllerTests.java
  src/test/java/com/mercadolibre/socialmeli/repository/UserRepositoryTests.java
  src/test/java/com/mercadolibre/socialmeli/service/UserServiceTests.java
Labels: Tamara approves, Fer approves

#35 Scrum 50 t 0011 mecozzi tamara
  src/test/java/com/mercadolibre/socialmeli/BeJavaHispW31G06ApplicationTests.java
  src/test/java/com/mercadolibre/socialmeli/controller/ProductsControllerTests.java
  src/test/java/com/mercadolibre/socialmeli/controller/UsersControllerTests.java
  src/test/java/com/mercadolibre/socialmeli/repository/ProductRepositoryTests.java
  src/test/java/com/mercadolibre/socialmeli/service/ProductServiceTest.java
  src/test/java/com/mercadolibre/socialmeli/service/UserServiceTests.java
  src/test/java/com/mercadolibre/socialmeli/util/TestDataFactory.java
Labels: Juani approves, Fer approves

#26 Implemento us 0008
  src/test/java/com/mercadolibre/socialmeli/controller/ProductsControllerTests.java
  src/test/java/com/mercadolibre/socialmeli/repository/UserRepositoryTests.java
  src/test/java/com/mercadolibre/socialmeli/service/ProductServiceTest.java
  src/test/java/com/mercadolibre/socialmeli/util/TestDataFactory.java
Labels: Juani approves, Tamara approves

#36 Implemento us 0009
  src/test/java/com/mercadolibre/socialmeli/controller/ProductsControllerTests.java
  src/test/java/com/mercadolibre/socialmeli/repository/UserRepositoryTests.java
  src/test/java/com/mercadolibre/socialmeli/service/ProductServiceTest.java
  src/test/java/com/mercadolibre/socialmeli/util/TestDataFactory.java
Labels: Fer approves

#38 Complementary test to assuer 85% of coverage
  src/main/java/com/mercadolibre/socialmeli/controller/ProductsController.java
  src/main/java/com/mercadolibre/socialmeli/dto/CreatePostDto.java
  src/main/java/com/mercadolibre/socialmeli/dto/MensajeDto.java
  src/main/java/com/mercadolibre/socialmeli/entity/Post.java
  src/main/java/com/mercadolibre/socialmeli/repository/IProductRepository.java
  src/main/java/com/mercadolibre/socialmeli/repository/ProductRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/repository/UserRepositoryImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/IUserService.java
  src/main/java/com/mercadolibre/socialmeli/service/ProductServiceImpl.java
  src/main/java/com/mercadolibre/socialmeli/service/UserServiceImpl.java
  src/test/java/com/mercadolibre/socialmeli/BeJavaHispW31G06ApplicationTests.java
  src/test/java/com/mercadolibre/socialmeli/controller/ProductsControllerTests.java
  src/test/java/com/mercadolibre/socialmeli/integration/IntegrationTests.java
  src/test/java/com/mercadolibre/socialmeli/repository/UserRepositoryTests.java
  src/test/java/com/mercadolibre/socialmeli/service/ProductServiceTest.java
  src/test/java/com/mercadolibre/socialmeli/service/UserServiceTests.java
  src/test/java/com/mercadolibre/socialmeli/util/TestDataFactory.java
Labels: Fer approves
